FROM node:22-alpine AS build
WORKDIR /src
COPY web /src/web

WORKDIR /src/web/buyer-web
RUN npm ci || npm install
ENV VITE_BASE=/
ENV VITE_API_BASE_URL=
RUN npm run build

WORKDIR /src/web/vendor-portal
RUN npm ci || npm install
ENV VITE_BASE=/vendor/
RUN npm run build

WORKDIR /src/web/delivery-portal
RUN npm ci || npm install
ENV VITE_BASE=/hub/
RUN npm run build

WORKDIR /src/web/super-admin
RUN npm ci || npm install
ENV VITE_BASE=/admin/
RUN npm run build

FROM nginx:1.27-alpine
COPY infra/nginx/qa.conf /etc/nginx/conf.d/default.conf
COPY --from=build /src/web/buyer-web/dist /usr/share/nginx/html/buyer
COPY --from=build /src/web/vendor-portal/dist /usr/share/nginx/html/vendor
COPY --from=build /src/web/delivery-portal/dist /usr/share/nginx/html/hub
COPY --from=build /src/web/super-admin/dist /usr/share/nginx/html/admin
EXPOSE 80
