-- Fill gaps for buyer status alerts (SMS + PUSH stubs; real providers later).
INSERT INTO notification_templates (event_code, channel, body_template, status) VALUES
    ('ITEM_RESTORED', 'SMS',
     'HyperLocalMart: {{itemName}} restored on order {{orderNumber}}. Rs {{amount}} debited from wallet.',
     'ACTIVE'),
    ('PAYMENT_FAILED', 'SMS',
     'HyperLocalMart: Payment failed for order {{orderNumber}}. Please try again or choose COD.',
     'ACTIVE'),
    ('ORDER_AT_HUB', 'SMS',
     'HyperLocalMart: Order {{orderNumber}} has reached our delivery hub and will be out for delivery soon.',
     'ACTIVE'),
    ('BUYER_REJECTED', 'SMS',
     'HyperLocalMart: Delivery of order {{orderNumber}} was marked as rejected. Reason: {{reason}}',
     'ACTIVE'),
    -- PUSH mirrors (dev stub / future FCM)
    ('ORDER_PLACED', 'PUSH',
     'Order {{orderNumber}} placed. Total Rs {{totalAmount}}.',
     'ACTIVE'),
    ('ORDER_CANCELLED', 'PUSH',
     'Order {{orderNumber}} cancelled. {{reason}}',
     'ACTIVE'),
    ('REFUND_INITIATED', 'PUSH',
     'Refund Rs {{amount}} started for {{orderNumber}}.',
     'ACTIVE'),
    ('SUB_ORDER_READY', 'PUSH',
     '{{shopName}} is ready (order {{orderNumber}}).',
     'ACTIVE'),
    ('OUT_FOR_DELIVERY', 'PUSH',
     'Order {{orderNumber}} is out for delivery. OTP {{otp}}.',
     'ACTIVE'),
    ('ORDER_DELIVERED', 'PUSH',
     'Order {{orderNumber}} delivered. Thank you!',
     'ACTIVE'),
    ('ITEM_CANCELLED_STORE_CREDIT', 'PUSH',
     '{{itemName}} cancelled on {{orderNumber}}. Rs {{amount}} credited (wallet Rs {{balance}}).',
     'ACTIVE'),
    ('ITEM_RESTORED', 'PUSH',
     '{{itemName}} restored on {{orderNumber}}. Rs {{amount}} from wallet.',
     'ACTIVE'),
    ('PAYMENT_FAILED', 'PUSH',
     'Payment failed for order {{orderNumber}}.',
     'ACTIVE'),
    ('ORDER_AT_HUB', 'PUSH',
     'Order {{orderNumber}} arrived at hub.',
     'ACTIVE'),
    ('BUYER_REJECTED', 'PUSH',
     'Delivery rejected for order {{orderNumber}}.',
     'ACTIVE')
ON CONFLICT (event_code, channel, language) DO NOTHING;
