INSERT INTO notification_templates (event_code, channel, body_template, status) VALUES
    ('CLAIM_OPENED', 'SMS',
     'HyperLocalMart: We received your claim on order {{orderNumber}} ({{claimType}} — {{itemName}}). Hub will review shortly.',
     'ACTIVE'),
    ('CLAIM_RESOLVED', 'SMS',
     'HyperLocalMart: Claim on {{orderNumber}} resolved. Rs {{amount}} store credit added for {{itemName}}.',
     'ACTIVE'),
    ('CLAIM_REJECTED', 'SMS',
     'HyperLocalMart: Claim on order {{orderNumber}} was not approved. {{reason}}',
     'ACTIVE'),
    ('CLAIM_OPENED', 'PUSH',
     'Claim filed on {{orderNumber}}: {{claimType}} ({{itemName}}).',
     'ACTIVE'),
    ('CLAIM_RESOLVED', 'PUSH',
     'Claim resolved on {{orderNumber}}. Rs {{amount}} credited.',
     'ACTIVE'),
    ('CLAIM_REJECTED', 'PUSH',
     'Claim on {{orderNumber}} not approved. {{reason}}',
     'ACTIVE');
